### PR TITLE
Add support for patch method

### PR DESCRIPTION
**Pull request by atoomic**
tested after merging the CI workflow from #19
you can view results here
https://github.com/atoomic/HTTP-Tinyish/actions/runs/103731278

### CODE REVIEW

**Comment by atoomic** [comment]
The error seen on Travis CI is related to issues when no backend can be tested and is fixed by #21

**Comment by atoomic** [comment]
@miyagawa are you planning to do a release with this change?

**Comment by miyagawa** [comment]
Yep, 0.16 shipped.

**Comment by atoomic** [comment]
thanks a lot you rock!

**Pull request merged**
