### PR TITLE
Add GitHub action for CI

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by atoomic** [comment]
not sure why Travis has a few Perl versions failing... this change should not be related to these errors
view results from my remote: https://github.com/atoomic/HTTP-Tinyish/actions/runs/103730778

**Comment by atoomic** [comment]
The error seen on Travis CI is related to issues when no backend can be tested and is fixed by #21

**Comment by miyagawa** [comment]
Thanks. Added GitHub actions via f276183

**Comment by atoomic** [comment]
perfect I was using the `perldocker/perl-tester` images which are preset with some common test modules and cpanm :-) [but was using another action to do the install]

**Pull request closed without merging**
